export enum habitatID {
  cave = 1,
  forest,
  grassland,
  mountain,
  rare,
  rough_terrain,
  sea,
  urban,
  waters_edge,
}
// Generated by https://quicktype.io
export interface pokeHabitats {
  name: string | null;
  pokemon_species: PokemonSpecies[] | null;
}

export interface PokemonHabitats {
  id: number;
  name: string;
  names: Name[];
  pokemon_species: PokemonSpecies[];
}

export interface Name {
  language: PokemonSpecies;
  name: string;
}

export interface PokemonSpecies {
  name: string;
  url: string;
}
